### ISSUE TITLE
Workflow dispatch support?

### ISSUE THREAD

**Issue by AntoniosBarotsis** [taiki-e/create-gh-release-action#19]
It would be convenient to _not_ require a `on: push: tags...` workflow trigger, I find myself using [workflow dispatch](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch) a lot and it would be great if this action could work with that :)

From what I understand, the action _needs_ a git tag to obtain the version number. A variable can be provided using a workflow dispatch trigger, you can see an example of a workflow I've written [here](https://github.com/AntoniosBarotsis/qr-rs/blob/master/.github/workflows/release-server.yml).

I'm not sure if this just works (in which case adding an example would be great) but if not I could try and help implement this with some guidance.

**Comment by taiki-e** [comment]
I think you can use ref input option: https://github.com/taiki-e/upload-rust-binary-action#supported-events

**Comment by AntoniosBarotsis** [comment]
That would still require a git tag to be created though right? Would it be possible for this to work by passing a commit as well?

**Comment by taiki-e** [comment]
Yeah, a GH release is associated with a tag, so a tag is required.

This action requires a tag to be present, but you can create and push a tag in the step before calling this action and then pass the ref of the created tag to this action.

**Comment by AntoniosBarotsis** [comment]
I see, I didn't know that releases require tags somehow so the whole issue doesn't really make sense. Thanks for the reply!
