### ISSUE TITLE
Will it fail if a changelog doesn't have the right version?

### ISSUE THREAD

**Issue by lmajano** [taiki-e/create-gh-release-action#22]
Will the build step fail if you specify a `changelog.md` but the tag you are building is not in the file?

Is there a way, to allow it to pass even if the changelog doesn't contain the tag version?

**Comment by taiki-e** [comment]
In the current implementation, if the changelog option is specified, an entry corresponding to the version must be present in the changelog.

That said, I think it would be easy to add an option to allow cases where the corresponding changelog entry is missing.
Probably it needs to change the following line to return an empty string if the option to allow missing entry is set.
https://github.com/taiki-e/create-gh-release-action/blob/0a3a16aba523e2d3ff92a744269fc789c14df703/main.sh#L113

Something like:

```sh
if [[ -n "${INPUT_ALLOW_MISSING_CHANGELOG_ENTRY:-}" ]]; then
    notes=$(./parse-changelog "${parse_changelog_options[@]}" || echo "") 
else
    notes=$(./parse-changelog "${parse_changelog_options[@]}") 
fi
