### ISSUE TITLE
Can you change the Rocket to custom icon?

### ISSUE THREAD

**Issue by oiricaud** [taiki-e/create-gh-release-action#30]
I am interested in notifying Instana on releases but also on new commits or even pull requests. However the rocket icon could be misleading if I am using a GitHub action to push and notify Instana that I had made a new change.

**Comment by oiricaud** [comment]
You can see here I committed some changes but it displays a rocket <img width="902" alt="Screenshot 2023-07-26 at 17 00 38" src="https://github.com/taiki-e/create-gh-release-action/assets/11867058/5f049bf0-12c8-4391-aaa0-8729d864e0c1">

**Comment by taiki-e** [comment]
It appears that you are submitting the issue to an unrelated repository.
