### ISSUE TITLE
Actions failing while releasing binary

### ISSUE THREAD

**Issue by orzklv** [taiki-e/create-gh-release-action#31]
I've been trying to release my compiler and actions failing while searching variable INPUT_TARGET

The yaml file: https://github.com/osmon-lang/havo/blob/main/.github/workflows/release.yml

```
Run taiki-e/setup-cross-toolchain-action@v1
Run bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
  bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_TARGET: 
    INPUT_RUNNER: 
/home/runner/work/_actions/taiki-e/setup-cross-toolchain-action/v1/main.sh: line 40: INPUT_TARGET: parameter null or not set
Error: Process completed with exit code 1.
```

**Comment by taiki-e** [comment]
You have to pass `target: ${{ matrix.target }}` to setup-cross-toolchain-action.

https://github.com/osmon-lang/havo/blob/371239b4110733ddd772e5d509344aff52f4531a/.github/workflows/release.yml#L39

**Comment by orzklv** [comment]
thank you very much, worked!
